language: php
php:
  - 5.5
  - 5.4
before_script:
  - composer install
  - npm install karma
  - npm install karma-jasmine
  - npm install karma-phantomjs-launcher
  - npm install karma-spec-reporter
  - npm install karma-coverage
  - npm install karma-coveralls
  - npm install -g bower
  - bower install
script:
  - ./node_modules/karma/bin/karma start --single-run --browsers PhantomJS /home/travis/build/jblotus/PlanningPoker/karma.conf.js
  - /home/travis/build/jblotus/PlanningPoker/vendor/bin/phpunit --bootstrap /home/travis/build/jblotus/PlanningPoker/tests/bootstrap.php /home/travis/build/jblotus/PlanningPoker/tests/src


