language: php
php:
  - 5.5
  - 5.4
  - hhvm
before_script:
  - composer install
script:
  - /home/travis/build/jblotus/PlanningPoker/vendor/bin/phpunit --bootstrap /home/travis/build/jblotus/PlanningPoker/tests/bootstrap.php /home/travis/build/jblotus/PlanningPoker/tests/src


