language: php
php:
  - 5.5
  - 5.4
  - hhvm
before_script:
  - npm install karma
  - composer install
script:
  - ./vendor/bin/phpunit tests --bootstrap tests/bootstrap.php
  - ./node_modules/.bin/karma start --single-run --browsers PhantomJS karma.conf.js


