language: php
php:
  - 5.5
  - 5.4
before_script:
  - composer install
  - npm install karma
script:
  - ./node_modules/karma/bin/karma
  - /home/travis/build/jblotus/PlanningPoker/vendor/bin/phpunit --bootstrap /home/travis/build/jblotus/PlanningPoker/tests/bootstrap.php /home/travis/build/jblotus/PlanningPoker/tests/src


